export const CREATE_NEW_ROOM = 'CREATE_NEW_ROOM';
export const CONNECT_TO_ROOM = 'CONNECT_TO_ROOM';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const PLAYER_MOVE = 'PLAYER_MOVE';
export const COMPETITOR_CONNECTED = 'COMPETITOR_CONNECTED';
export const COMPETITOR_LEFT = 'COMPETITOR_LEFT';